version: "3"
services:
  app:
    container_name: dev_nextjs_template_app
    build:
      context: ./
      dockerfile: Dockerfile.local
    stdin_open: true
    tty: true
    command: npm run dev
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    networks:
      - dev_nextjs_template_network

  # storybook:
  #   container_name: dev_nextjs_template_storybook
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.dev
  #   command: yarn storybook
  #   tty: true
  #   volumes:
  #     - ./:/var/www
  #   ports:
  #     - '6006:6006'
  #   networks:
  #     - dev_nextjs_template_network

  # db:
  #   container_name: dev_nextjs_template_db
  #   image: postgres:14.6
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: hmadmin
  #     POSTGRES_PASSWORD: password
  #     PGPASSWORD: password
  #     POSTGRES_DB: human_manage_development
  #     TZ: "Asia/Tokyo"
  #   volumes:
  #     - dev_nextjs_template_db_volume:/var/lib/postgresql/data
  #   networks:
  #     - dev_nextjs_template_network

networks:
  dev_nextjs_template_network:
    external: true

volumes:
  dev_nextjs_template_db_volume:
